name: Test core functionality of image

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      image_os:
        required: true
        type: string
      arch:
        required: true
        type: string

jobs:
  test_image:
    uses: ./.github/workflows/test_image.yml
    with:
      runner: ${{ inputs.runner }}
      image_os: ${{ inputs.image_os }}
      arch: ${{ inputs.arch }}

  test_save_cache:
    uses: ./.github/workflows/test_save_cache.yml
    with:
      runner: ${{ inputs.runner }}
      image_os: ${{ inputs.image_os }}
      arch: ${{ inputs.arch }}

  test_restore_cache:
    needs: test_save_cache
    uses: ./.github/workflows/test_restore_cache.yml
    with:
      runner: ${{ inputs.runner }}
      image_os: ${{ inputs.image_os }}
      arch: ${{ inputs.arch }}
